---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: stop existing app if it is running
    shell: docker ps -q -f name=insure-me && docker stop insure-me && docker rm insure-me || true

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me aaronmathews95/insure-me:1.0.0
